// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickQuiz2.Data;

#nullable disable

namespace QuickQuiz2.Migrations
{
    [DbContext(typeof(QuickQuizDbContext))]
    [Migration("20230828100942_TestSeed")]
    partial class TestSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickQuiz2.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardDiffDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Elephant",
                            Category = "Animal",
                            Description = "Introducing the incredible elephant! These gentle giants are found in various parts of the world, like Africa and Asia. They're the largest land animals on Earth and can weigh as much as a few cars put together! Elephants are super smart and have big, floppy ears that help them keep cool. When it's hot, they spray themselves with water using their trunks, which are like their own personal water hoses. These plant-eating pals have a huge appetite and love munching on leaves, grass, and fruits. Elephants live in close-knit families called herds, where they look out for each other. Just like us, they're curious and full of surprises!",
                            HardDiffDesc = "I'm a gentle giant found in places like Africa and Asia. I'm the biggest land animal, with floppy ears, a long trunk, and I love eating plants. Who am I?",
                            ImagePath = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
