// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickQuiz2.Data;

#nullable disable

namespace QuickQuiz2.Migrations
{
    [DbContext(typeof(QuickQuizDbContext))]
    [Migration("20230829081138_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickQuiz2.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardDiffDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Elephant",
                            Category = "Animals",
                            Description = "Introducing the incredible elephant! These gentle giants are found in various parts of the world, like Africa and Asia. They're the largest land animals on Earth and can weigh as much as a few cars put together! Elephants are super smart and have big, floppy ears that help them keep cool. When it's hot, they spray themselves with water using their trunks, which are like their own personal water hoses. These plant-eating pals have a huge appetite and love munching on leaves, grass, and fruits. Elephants live in close-knit families called herds, where they look out for each other. Just like us, they're curious and full of surprises!",
                            HardDiffDesc = "I'm a gentle giant found in places like Africa and Asia. I'm the biggest land animal, with floppy ears, a long trunk, and I love eating plants. Who am I?",
                            ImagePath = "elephant.png"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Crocodile",
                            Category = "Animals",
                            Description = "Meet the amazing crocodile! These fascinating reptiles can be found in warm places around the world, like Africa, Asia, and Australia. Crocs love hanging out near water, like rivers and swamps. They're like living dinosaurs with tough, scaly skin and powerful jaws. Crocodiles are fantastic swimmers and often stay hidden underwater, waiting for their next meal. Speaking of meals, they're carnivores, which means they eat meat. From fish to birds, they have a diverse menu! Crocodiles can grow to be really big, sometimes over 20 feet long! Remember, while they might look scary, they're an important part of their ecosystems. Give them their space when you spot one!",
                            HardDiffDesc = "I'm a tough reptile found in warm places around the world like Africa and Asia. I have scaly skin, powerful jaws, and love swimming in rivers. What am I?",
                            ImagePath = "crocodile.png"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Hammerhead Shark",
                            Category = "Animals",
                            Description = "Dive into the world of hammerhead sharks! These cool creatures swim in the oceans around the globe, from warm tropical waters to cooler seas. What makes them stand out are their hammer-shaped heads, which are like underwater radar! This shape helps them find food, like squids and fish, even in the dark depths of the ocean. Hammerheads are strong swimmers and often travel in groups called schools. They're not usually interested in bothering humans, so if you spot one, it's best to just admire from a distance. These sharks might look a little strange, but they're perfectly designed for life underwater!",
                            HardDiffDesc = "Dive into the ocean world with an amazing creature known for its hammer-shaped head! This special feature helps it find food and swim together with its friends. Can you guess what this unique underwater animal is?",
                            ImagePath = "hammerhead.png"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Raccoon",
                            Category = "Animals",
                            Description = "Get ready to meet the clever raccoon! These furry friends are found in North and Central America. Raccoons are famous for their mask-like markings around their eyes, making them look like little bandits. They're skilled climbers and love hanging out in forests, near rivers, and even in cities. Raccoons are omnivores, which means they eat both plants and animals. They have tiny 'hands' that they use to grab and explore things, just like us! These nocturnal creatures are most active at night and have a knack for finding food anywhere. Whether they're washing their meals or solving puzzles, raccoons are known for their intelligence and adaptability.",
                            HardDiffDesc = "A clever creature with mask-like markings around its eyes, as if it's a little bandit! This furry friend is skilled at climbing, exploring, and finding food anywhere. Can you guess which resourceful animal this is?",
                            ImagePath = "raccoon.png"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Quokka",
                            Category = "Animals",
                            Description = "Get ready to meet the adorable quokka, a special animal found in Australia! Quokkas are famous for their friendly smiles and bouncy moves. You can spot them on Rottnest Island, their cozy home. These little marsupials are like mini kangaroos, but extra cute! Quokkas are herbivores, which means they love munching on plants, leaves, and yummy grasses. They're about the size of a cat or small dog, making them perfect pocket-sized pals. Remember, if you see a quokka, let them enjoy their island paradise in peace and take a picture from a safe distance!",
                            HardDiffDesc = "Meet a special animal from Australia! It has a friendly smile, loves plants, and is about the size of a small dog. Can you guess what it is?",
                            ImagePath = "quokka.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
